<h1 class="display-5">Сайт: <?= htmlspecialchars($site->getName()) ?></h1>
<table class="table table-bordered" data-test="url">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col"><?= htmlspecialchars($site->getId()) ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Имя</th>
            <td><?= htmlspecialchars($site->getName()) ?></td>
        </tr>
        <tr>
            <th scope="row">Дата создания</th>
            <td><?= htmlspecialchars($site->getCreatedAt()->format('Y-m-d')) ?></td>
        </tr>
    </tbody>
</table>
<br>
<h1 class="display-5">Проверки</h1>
<table class="table table-bordered" data-test="checks">
    <thead>
        <tr>
            <th scope="col">1</th>
            <th scope="col">2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">3</th>
            <td>4</td>
        </tr>
        <tr>
            <th scope="row">5</th>
            <td>6</td>
        </tr>
    </tbody>
</table>