<h1 class="display-5">Сайты</h1>
<table class="table table-bordered" data-test="urls">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Имя</th>
            <th scope="col">Последняя проверка</th>
            <th scope="col">Код ответа</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($urls as $url) : ?>
        <tr>
            <th scope="row"><?= $url->getId() ?></th>
            <td>
                <a href="/urls/<?= $url->getId() ?>">
                    <?= htmlspecialchars($url->getName()) ?>
                </a>
            </td>
            <td></td>
            <td></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
