<h1 class="display-5">Сайты</h1>
<table class="table table-bordered" data-test="urls">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Имя</th>
            <th scope="col">Последняя проверка</th>
            <th scope="col">Код ответа</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($urls as $url) : ?>
        <tr>
            <th scope="row"><?= e($url->getId()) ?></th>
            <td>
                <a href="<?= e($routeParser->urlFor('urls.show', ['id' => $url->getId()])) ?>">
                    <?= e($url->getName()) ?>
                </a>
            </td>
            <td>
                <?= $lastChecks[$url->getId()]["created_at"] ?>
            </td>
            <td>
                <?= $lastChecks[$url->getId()]["status_code"] ?>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
