<h1 class="display-5">Сайт: <?= e($url->getName()) ?></h1>
<table class="table table-bordered" data-test="url">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col"><?= e($url->getId()) ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Имя</th>
            <td><?= e($url->getName()) ?></td>
        </tr>
        <tr>
            <th scope="row">Дата создания</th>
            <td><?= e($url->getCreatedAt()->format('Y-m-d H:i:s')) ?></td>
        </tr>
    </tbody>
</table>
<br>
<h1 class="display-5">Проверки</h1>
<form method="post" action="<?= e($routeParser->urlFor('urls.show.checks', ['url_id' => $url->getId()])) ?>">
    <input class="btn btn-primary" type="submit" value="Запустить проверку">
</form>
<table class="table table-bordered" data-test="checks">
    <thead>
        <tr>
            <th>ID</th>
            <th>Код ответа</th>
            <th>h1</th>
            <th>title</th>
            <th>description</th>
            <th>Дата создания</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($checks as $check) : ?>
        <tr>
            <td><?= e($check->getId()) ?></td>
            <td><?= e((string) $check->getStatusCode()) ?? '' ?></td>
            <td><?= truncate(e($check->getH1() ?? ''), 200) ?></td>
            <td><?= truncate(e($check->getTitle() ?? ''), 200) ?></td>
            <td><?= truncate(e($check->getDescription() ?? ''), 200) ?></td>
            <td><?= e($check->getCreatedAt()->format('Y-m-d H:i:s')) ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
