<h1 class="display-5">Сайт: <?= htmlspecialchars($url->getName()) ?></h1>
<table class="table table-bordered" data-test="url">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col"><?= htmlspecialchars($url->getId()) ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Имя</th>
            <td><?= htmlspecialchars($url->getName()) ?></td>
        </tr>
        <tr>
            <th scope="row">Дата создания</th>
            <td><?= htmlspecialchars($url->getCreatedAt()->format('Y-m-d H:i:s')) ?></td>
        </tr>
    </tbody>
</table>
<br>
<h1 class="display-5">Проверки</h1>
<form method="post" action="<?= htmlspecialchars($routeParser->urlFor('urls.id.checks', ['url_id' => $url->getId()])) ?>">
    <input class="btn btn-primary" type="submit" value="Запустить проверку">
</form>
<table class="table table-bordered" data-test="checks">
    <thead>
        <tr>
            <th>ID</th>
            <th>Код ответа</th>
            <th>h1</th>
            <th>title</th>
            <th>description</th>
            <th>Дата создания</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>200</td>
            <td>...</td>
            <td>...</td>
            <td>...</td>
            <td>2024-01-01</td>
        </tr>
    </tbody>
</table>
