<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор Страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a href="/" class="navbar-brand mb-0 h1">Анализатор страниц</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="<?= htmlspecialchars($routeParser->urlFor('urls.new')) ?>">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= htmlspecialchars($routeParser->urlFor('urls.index')) ?>">Сайты</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <main class="container flex-grow-1">
        <!-- flash -->
        <?php if (isset($flash) && count($flash) > 0) : ?>
            <?php foreach ($flash as $key => $messages) : ?>
                <?php foreach ($messages as $message) : ?>
                    <div class="alert alert-<?= htmlspecialchars($key) ?>" role="alert">
                        <?= htmlspecialchars($message) ?>
                    </div>
                <?php endforeach ?>
            <?php endforeach ?>
        <?php elseif (isset($error)): ?>
            <div class="alert alert-<?= htmlspecialchars($error['key']) ?>" role="alert">
                <?= htmlspecialchars($error['message']) ?>
            </div>
        <?php endif; ?>
        <!-- content -->
        <?= $content ?>
    </main>
    <footer class="text-center border border-2 p-2">
        <a href="<?= htmlspecialchars($routeParser->urlFor('urls.new')) ?>">Hexlet</a>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>
