<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-xl-8">
            <div class="border rounded-3 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead mb-4">Бесплатно проверяйте сайты на SEO-пригодность</p>
                <form>
                    <div class="row g-3">
                        <div class="col">
                            <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="https://www.example.com">
                        </div>
                        <div class="col-auto">
                            <button type="submit" class="btn btn-primary px-5">ПРОВЕРИТЬ</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>